# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todo_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todo_app
  pod 'SwiftLint'

  target 'todo_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todo_appUITests' do
    # Pods for testing
  end

end
